### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alexmyczko** [deb0ch/R-Type#1]
Is this free software, and can be distributed with a Linux distribution?

**Comment by deb0ch** [comment]
If it is not it should be, I made this project with a few friends so I need to ask them first but on my end it is 100% OK

**Comment by alexmyczko** [comment]
btw did you know about https://github.com/ptitSeb/prototype ?

**Comment by deb0ch** [comment]
I didn't know about this project at all 😅What about it ?

I will get in touch with the friends I made this project with maybe tonight, and add a license as soon as I can. I'm thinking maybe MIT or Apache, or even maybe GPL I don't know yet.

**Comment by alexmyczko** [comment]
Well it's one more R-Type remake... that guy also has a Stunt Car Racer remake, and some more stuff with SDL2...

Sounds great, have fun! Personally I like the GPL2+ or WTFPL because they are short and easy, however MIT should be fine too. I have not read the Apache license (and never packaged any apache licensed software) - prefer nginx.

**Comment by deb0ch** [comment]
Hi !

I finally got an answer of all co-authors and will upload a WTFPL licence as soon as I have some time for it !

Happy new year 🎉

**Comment by alexmyczko** [comment]
You didn't add the license to the project yet, did you?

**Comment by deb0ch** [comment]
Hahaha, you got me 😅 It's done now, I just added it. I hope I did it right, I just copy/pasted the license text verbatim into a LICENSE file at the root of the project.
