### ISSUE TITLE
Bulid error on Arch Linux

### ISSUE THREAD

**Issue by EvanKoe** [deb0ch/R-Type#4]
![image](https://user-images.githubusercontent.com/72010109/191017826-46e71ca2-c47e-4818-ba65-b538e487a25c.png)

OS : Arch Linux
Kernel version : Linux 5.19.8

**Comment by deb0ch** [comment]
Hey ! This is a (very) old project, maybe your compiler is too recent for it. Try with an older one dating back circa the last few commits. If not same process for system libraries. Best would be to use docker to not mess up your system with old stuff, if you come up with a working dockerfile please submit it. Even better would be fixing the code of the project against recent compiler and libs

**Comment by deb0ch** [comment]
But, as a current Epitech student yourself and a former one myself, I would recommend to code your own RType.

You are very welcome to take inspiration from how we architectured the project, we put a lot of thought in our Entity-Component-System and were even able to add levels or create a PvP mode without recompiling the game. Maybe cheating was never your intention, but in case, copy-and-modifying the code to evade cheat detection might take you even longer than coding the project yourself, and you wouldn't learn anything doing it this way. Going from your own blank page is better on all points of view.

By the way, I am still a teacher at Epitech 😉 Maybe see you IRL someday 👋

**Comment by EvanKoe** [comment]
Thanks for your advices ! Of course I'm doing my own RType, I was just trying to build your repo in order to test it (I have no idea what a RType is, and what are the controls...).
I took inspiration especially from your ECS architecture. But I won't copy/paste anything, don't worry !
